import Foundation

/// 介面字串對照表。
///
/// key 一律使用英文識別碼（例如 `general.section.permissions`），不要用譯文當 key，
/// 這樣任何語言的文案調整都不會影響查表。查不到時退回英文，再查不到才回傳 key 本身。
enum UIStrings {
    static let table: [SupportedLanguage: [String: String]] = [
        .zhHant: zhHant,
        .zhHans: zhHans,
        .en: en,
        .ja: ja,
        .ko: ko,
    ]

    // MARK: - 繁體中文

    static let zhHant: [String: String] = [
        // 視窗與選單
        "menu.hold-to-speak": "按住%@說話",
        "menu.preferences": "偏好設定...",
        "menu.quit": "結束 TypeTop",
        "window.preferences": "TypeTop 偏好設定",
        "tab.general": "一般",
        "tab.api": "API 設定",
        "tab.language": "語言",
        "tab.vocabulary": "詞彙庫",

        // 通用
        "common.cancel": "取消",
        "common.save": "儲存",
        "common.add": "新增",
        "common.ok": "確定",
        "common.reset-default": "重置為預設",

        // 一般頁
        "general.section.shortcut": "快捷鍵",
        "general.push-to-talk-key": "按住說話快捷鍵",
        "general.interface-language": "介面語言",
        "general.section.permissions": "權限",
        "general.accessibility": "輔助使用權限",
        "general.microphone": "麥克風權限",
        "general.granted": "已授權",
        "general.open-settings": "前往設定",
        "general.request-access": "請求權限",
        "general.section.behavior": "行為",
        "general.play-sounds": "播放音效提示",
        "general.mute-system-audio": "錄音時靜音系統音訊",
        "general.launch-at-login": "開機自動啟動",
        "general.section.about": "關於",
        "general.version": "版本",
        "general.tagline": "語音輸入，好好打字",

        // 啟動鍵
        "key.right-command": "右側 ⌘",
        "key.left-command": "左側 ⌘",
        "key.right-option": "右側 ⌥",
        "key.left-option": "左側 ⌥",
        "key.right-control": "右側 ⌃",
        "key.left-control": "左側 ⌃",

        // API 頁
        "api.section.stt": "語音辨識（STT）— Groq",
        "api.section.llm": "語意修正（LLM）— %@",
        "api.test-connection": "測試連線",
        "api.test-llm-connection": "測試 LLM 連線",
        "api.model": "模型",
        "api.model-name": "模型名稱",
        "api.status": "狀態",
        "api.available": "可用",
        "api.llm-provider": "LLM 供應商",
        "api.open-groq-console": "開啟 Groq Console",
        "api.open-website": "開啟 %@ 官網",
        "api.howto.title": "如何取得 Groq API Key：",
        "api.howto.step1": "1. 前往 console.groq.com 註冊／登入",
        "api.howto.step2": "2. 左側選單點「API Keys」→「Create API Key」",
        "api.howto.step3": "3. 複製 gsk_ 開頭的 Key 貼到上方欄位",
        "api.howto.multi-account": "可新增多組不同帳號的 Key，達免費額度時會自動切換。",
        "api.failover-note": "達額度上限（HTTP 429）時會自動切換到下一組帳號。",
        "api.add-account": "新增帳號",
        "api.account-n": "帳號 %d",
        "api.account-name": "帳號名稱",
        "api.name": "名稱",
        "api.in-use": "使用中",
        "api.set-active": "設為使用中",
        "api.edit-key": "檢視／編輯名稱與 Key",
        "api.collapse": "收合",
        "api.delete-account": "刪除此帳號",
        "api.copy-message": "複製訊息",

        // 用量
        "usage.section": "今日用量（本地統計）",
        "usage.stt": "語音辨識（%@）",
        "usage.llm": "語意修正（%@）",
        "usage.requests": "%@ 次",
        "usage.requests-tokens": "%@ 次 / %@ tokens",
        "usage.groq-stt-remaining": "Groq 語音辨識剩餘額度%@",
        "usage.groq-llm-remaining": "Groq 語意修正剩餘額度%@",
        "usage.note": "次數與 tokens 為本 app 的本地統計，僅計入目前使用中的帳號；Groq 剩餘額度來自官方回應。其他供應商的官方額度請至各家控制台查看（Gemini：aistudio.google.com/rate-limit）。",

        // 測試結果
        "test.stt-ok": "Groq STT 連線成功！（%@ 秒%@）",
        "test.stt-fail": "Groq STT：%@",
        "test.apple-ok": "Apple 本機模型可用！（回應：%@）",
        "test.apple-fail": "Apple 本機模型：%@",
        "test.llm-ok": "%@ LLM 連線成功！（回應：%@%@）",
        "test.llm-fail": "%@ LLM：%@",

        // 語言頁
        "lang.section.primary": "主要語言",
        "lang.recognition-language": "辨識語言",
        "lang.mixed-mode": "中英文混合模式",
        "lang.mixed-mode-note": "啟用混合模式後，Whisper 會同時辨識主要語言和英文內容",
        "lang.section.text": "文字處理",
        "lang.auto-space": "中英文之間自動加空格",
        "lang.auto-space-note": "例如「使用React框架」→「使用 React 框架」",
        "lang.punctuation-style": "標點符號風格",
        "lang.punctuation-note": "全形：，。！？　半形：,.!?　無標點：移除全部　保持原樣：不轉換",
        "lang.section.whisper-prompt": "Whisper 提示詞",
        "lang.whisper-prompt-note": "提示詞幫助 Whisper 理解語境，可加入常用專有名詞以提升辨識準確度。例如輸入「TypeTop, React, Python」，Whisper 會優先辨識這些詞彙。",
        "lang.section.llm": "LLM 語意後處理",
        "lang.enable-llm": "啟用 LLM 智慧修正",
        "lang.model-in-use": "使用模型",
        "lang.need-api-key": "請先在 API 設定頁面輸入 %@ 的 API Key",
        "lang.provider-note": "語音辨識（STT）和語意修正（LLM）可使用不同供應商。例如 Groq 做語音轉文字、OpenAI GPT 做智慧修正。",
        "lang.temperature": "取樣溫度",
        "lang.temperature-note": "溫度越低輸出越穩定，越高越有變化。錯字修正建議 0~0.3。",
        "lang.section.system-prompt": "LLM 系統提示詞",
        "lang.correction-level": "修正程度",
        "lang.level-note": "選擇修正程度會自動套用預設提示詞，也可手動編輯。",
        "lang.reset-level-default": "重置為目前程度的預設",

        // 詞彙庫
        "vocab.search": "搜尋詞彙...",
        "vocab.count": "%@ 筆詞彙",
        "vocab.export-json": "匯出詞彙庫 (JSON)...",
        "vocab.export-zhuyin": "匯出注音詞庫 (.txt)...",
        "vocab.import": "匯入詞彙庫...",
        "vocab.empty-title": "沒有詞彙",
        "vocab.empty-line1": "點擊 + 新增自訂詞彙替換規則",
        "vocab.empty-line2": "用於修正語音辨識經常出錯的詞彙\n例如：「太好了 → TypeTop」「派森 → Python」",
        "vocab.import-error": "匯入錯誤",
        "vocab.default-filename": "個人詞庫.txt",
        "vocab.new-entry": "新增詞彙",
        "vocab.edit-entry": "編輯詞彙",
        "vocab.source": "辨識錯誤文字（來源）",
        "vocab.target": "正確文字（目標）",
        "vocab.note": "備註（選填）",
        "vocab.enabled": "啟用",

        // 狀態
        "state.idle": "就緒",
        "state.recording": "錄音中",
        "state.recording-ellipsis": "錄音中...",
        "state.transcribing": "辨識中",
        "state.transcribing-ellipsis": "辨識中...",
        "state.cancelled": "已取消",
        "state.done": "完成：%@...",
        "state.error": "錯誤：%@",

        // 修正程度
        "level.none": "無修正",
        "level.light": "輕微",
        "level.medium": "中等",
        "level.heavy": "重度",
        "level.none.desc": "僅加標點符號，完全保留原文",
        "level.light.desc": "修正錯字、加標點，保留口語風格",
        "level.medium.desc": "改寫為書面語，去除贅詞",
        "level.heavy.desc": "大幅精煉，重組句子結構",

        // 標點
        "punct.full": "全形標點",
        "punct.half": "半形標點",
        "punct.none": "無標點符號",
        "punct.keep": "保持原樣",

        // LLM 供應商
        "provider.apple": "Apple 本機模型",
        "provider.ollama": "Ollama (本地)",
        "provider.custom": "自訂",
        "provider.apple-model": "系統內建模型（on-device）",
        "provider.custom-key-placeholder": "API Key（若需要）",
        "provider.help.openai": "前往 platform.openai.com → API Keys → Create new secret key。需預先儲值，使用 gpt-4o-mini 費用極低。",
        "provider.help.groq": "前往 console.groq.com → API Keys → Create API Key。Groq 提供免費額度，日常使用綽綽有餘。",
        "provider.help.deepseek": "前往 platform.deepseek.com → API Keys。DeepSeek 提供高性價比的中文 LLM。",
        "provider.help.moonshot": "前往 platform.moonshot.ai → API Keys。Moonshot (Kimi) 支援中文語境最佳化。",
        "provider.help.gemini": "前往 aistudio.google.com → Get API Key。Gemini 提供免費額度。",
        "provider.help.apple": "使用 macOS 26 內建的 Apple Intelligence 本機模型（約 3B）。免費、離線可用、內容不離開這台電腦。需 Apple Silicon 並在「系統設定」開啟 Apple Intelligence。",
        "provider.help.ollama": "請確保 Ollama 已在本機執行（預設 http://localhost:11434）。不需要 API Key。",
        "provider.help.custom": "填入相容 OpenAI Chat Completions API 格式的 endpoint URL 和模型名稱。",

        // 錯誤
        "error.no-api-key": "未設定 API Key",
        "error.invalid-response": "API 回應格式錯誤",
        "error.api": "API 錯誤：%@",
        "error.network": "網路錯誤：%@",
        "error.empty-audio": "音訊資料為空",
        "error.rate-limited": "已達 API 用量上限（HTTP 429）",
        "error.llm-invalid-response": "LLM API 回應格式錯誤",
        "error.llm-api": "LLM API 錯誤：%@",
        "error.llm-rate-limited": "已達 LLM API 用量上限（HTTP 429）",
        "error.invalid-url": "無效的 URL: %@",
        "error.unknown": "未知錯誤",
        "error.apple.os-version": "需要 macOS 26 以上版本",
        "error.apple.unsupported-device": "此裝置不支援 Apple Intelligence（需 Apple Silicon）",
        "error.apple.not-enabled": "請先在「系統設定」開啟 Apple Intelligence",
        "error.apple.model-not-ready": "模型準備中（可能正在下載），請稍後再試",
        "error.apple.unavailable": "Apple Intelligence 目前無法使用",

        // 額度提示
        "quota.title": "%@ 已達用量上限",
        "quota.llm-switch": "語意修正（LLM）供應商 %@ 的所有帳號均回報已達額度上限（HTTP 429）。要切換到 %@ 嗎？",
        "quota.llm-none": "語意修正（LLM）供應商 %@ 的所有帳號均回報已達額度上限（HTTP 429）。沒有其他已設定 API Key 的供應商可切換，請至「API 設定」新增其他供應商或帳號的 Key。",
        "quota.stt-switch": "語音辨識（STT）供應商 %@ 的所有帳號均回報已達額度上限（HTTP 429）。要切換到 %@ 嗎？",
        "quota.stt-none": "語音辨識（STT）供應商 %@ 的所有帳號均回報已達額度上限（HTTP 429）。沒有其他已設定 API Key 的供應商可切換，請至「API 設定」新增其他供應商或帳號的 Key。",
        "quota.switch-to": "切換到 %@",
        "quota.later": "稍後再說",
        "quota.got-it": "知道了",
    ]

    // MARK: - 简体中文

    static let zhHans: [String: String] = [
        "menu.hold-to-speak": "按住%@说话",
        "menu.preferences": "偏好设置...",
        "menu.quit": "退出 TypeTop",
        "window.preferences": "TypeTop 偏好设置",
        "tab.general": "通用",
        "tab.api": "API 设置",
        "tab.language": "语言",
        "tab.vocabulary": "词汇库",

        "common.cancel": "取消",
        "common.save": "保存",
        "common.add": "添加",
        "common.ok": "确定",
        "common.reset-default": "重置为默认",

        "general.section.shortcut": "快捷键",
        "general.push-to-talk-key": "按住说话快捷键",
        "general.interface-language": "界面语言",
        "general.section.permissions": "权限",
        "general.accessibility": "辅助功能权限",
        "general.microphone": "麦克风权限",
        "general.granted": "已授权",
        "general.open-settings": "前往设置",
        "general.request-access": "请求权限",
        "general.section.behavior": "行为",
        "general.play-sounds": "播放音效提示",
        "general.mute-system-audio": "录音时静音系统音频",
        "general.launch-at-login": "开机自动启动",
        "general.section.about": "关于",
        "general.version": "版本",
        "general.tagline": "语音输入，好好打字",

        "key.right-command": "右侧 ⌘",
        "key.left-command": "左侧 ⌘",
        "key.right-option": "右侧 ⌥",
        "key.left-option": "左侧 ⌥",
        "key.right-control": "右侧 ⌃",
        "key.left-control": "左侧 ⌃",

        "api.section.stt": "语音识别（STT）— Groq",
        "api.section.llm": "语义修正（LLM）— %@",
        "api.test-connection": "测试连接",
        "api.test-llm-connection": "测试 LLM 连接",
        "api.model": "模型",
        "api.model-name": "模型名称",
        "api.status": "状态",
        "api.available": "可用",
        "api.llm-provider": "LLM 供应商",
        "api.open-groq-console": "打开 Groq Console",
        "api.open-website": "打开 %@ 官网",
        "api.howto.title": "如何获取 Groq API Key：",
        "api.howto.step1": "1. 前往 console.groq.com 注册／登录",
        "api.howto.step2": "2. 左侧菜单点「API Keys」→「Create API Key」",
        "api.howto.step3": "3. 复制 gsk_ 开头的 Key 粘贴到上方栏位",
        "api.howto.multi-account": "可添加多组不同账号的 Key，达免费额度时会自动切换。",
        "api.failover-note": "达额度上限（HTTP 429）时会自动切换到下一组账号。",
        "api.add-account": "添加账号",
        "api.account-n": "账号 %d",
        "api.account-name": "账号名称",
        "api.name": "名称",
        "api.in-use": "使用中",
        "api.set-active": "设为使用中",
        "api.edit-key": "查看／编辑名称与 Key",
        "api.collapse": "收起",
        "api.delete-account": "删除此账号",
        "api.copy-message": "复制消息",

        "usage.section": "今日用量（本地统计）",
        "usage.stt": "语音识别（%@）",
        "usage.llm": "语义修正（%@）",
        "usage.requests": "%@ 次",
        "usage.requests-tokens": "%@ 次 / %@ tokens",
        "usage.groq-stt-remaining": "Groq 语音识别剩余额度%@",
        "usage.groq-llm-remaining": "Groq 语义修正剩余额度%@",
        "usage.note": "次数与 tokens 为本 app 的本地统计，仅计入当前使用中的账号；Groq 剩余额度来自官方响应。其他供应商的官方额度请至各家控制台查看（Gemini：aistudio.google.com/rate-limit）。",

        "test.stt-ok": "Groq STT 连接成功！（%@ 秒%@）",
        "test.stt-fail": "Groq STT：%@",
        "test.apple-ok": "Apple 本机模型可用！（响应：%@）",
        "test.apple-fail": "Apple 本机模型：%@",
        "test.llm-ok": "%@ LLM 连接成功！（响应：%@%@）",
        "test.llm-fail": "%@ LLM：%@",

        "lang.section.primary": "主要语言",
        "lang.recognition-language": "识别语言",
        "lang.mixed-mode": "中英文混合模式",
        "lang.mixed-mode-note": "启用混合模式后，Whisper 会同时识别主要语言和英文内容",
        "lang.section.text": "文字处理",
        "lang.auto-space": "中英文之间自动加空格",
        "lang.auto-space-note": "例如「使用React框架」→「使用 React 框架」",
        "lang.punctuation-style": "标点符号风格",
        "lang.punctuation-note": "全角：，。！？　半角：,.!?　无标点：移除全部　保持原样：不转换",
        "lang.section.whisper-prompt": "Whisper 提示词",
        "lang.whisper-prompt-note": "提示词帮助 Whisper 理解语境，可加入常用专有名词以提升识别准确度。例如输入「TypeTop, React, Python」，Whisper 会优先识别这些词汇。",
        "lang.section.llm": "LLM 语义后处理",
        "lang.enable-llm": "启用 LLM 智能修正",
        "lang.model-in-use": "使用模型",
        "lang.need-api-key": "请先在 API 设置页面输入 %@ 的 API Key",
        "lang.provider-note": "语音识别（STT）和语义修正（LLM）可使用不同供应商。例如 Groq 做语音转文字、OpenAI GPT 做智能修正。",
        "lang.temperature": "采样温度",
        "lang.temperature-note": "温度越低输出越稳定，越高越有变化。错字修正建议 0~0.3。",
        "lang.section.system-prompt": "LLM 系统提示词",
        "lang.correction-level": "修正程度",
        "lang.level-note": "选择修正程度会自动套用默认提示词，也可手动编辑。",
        "lang.reset-level-default": "重置为当前程度的默认值",

        "vocab.search": "搜索词汇...",
        "vocab.count": "%@ 条词汇",
        "vocab.export-json": "导出词汇库 (JSON)...",
        "vocab.export-zhuyin": "导出注音词库 (.txt)...",
        "vocab.import": "导入词汇库...",
        "vocab.empty-title": "没有词汇",
        "vocab.empty-line1": "点击 + 添加自定义词汇替换规则",
        "vocab.empty-line2": "用于修正语音识别经常出错的词汇\n例如：「太好了 → TypeTop」「派森 → Python」",
        "vocab.import-error": "导入错误",
        "vocab.default-filename": "个人词库.txt",
        "vocab.new-entry": "添加词汇",
        "vocab.edit-entry": "编辑词汇",
        "vocab.source": "识别错误文字（来源）",
        "vocab.target": "正确文字（目标）",
        "vocab.note": "备注（选填）",
        "vocab.enabled": "启用",

        "state.idle": "就绪",
        "state.recording": "录音中",
        "state.recording-ellipsis": "录音中...",
        "state.transcribing": "识别中",
        "state.transcribing-ellipsis": "识别中...",
        "state.cancelled": "已取消",
        "state.done": "完成：%@...",
        "state.error": "错误：%@",

        "level.none": "无修正",
        "level.light": "轻微",
        "level.medium": "中等",
        "level.heavy": "重度",
        "level.none.desc": "仅加标点符号，完全保留原文",
        "level.light.desc": "修正错字、加标点，保留口语风格",
        "level.medium.desc": "改写为书面语，去除赘词",
        "level.heavy.desc": "大幅精炼，重组句子结构",

        "punct.full": "全角标点",
        "punct.half": "半角标点",
        "punct.none": "无标点符号",
        "punct.keep": "保持原样",

        "provider.apple": "Apple 本机模型",
        "provider.ollama": "Ollama (本地)",
        "provider.custom": "自定义",
        "provider.apple-model": "系统内置模型（on-device）",
        "provider.custom-key-placeholder": "API Key（如需要）",
        "provider.help.openai": "前往 platform.openai.com → API Keys → Create new secret key。需预先充值，使用 gpt-4o-mini 费用极低。",
        "provider.help.groq": "前往 console.groq.com → API Keys → Create API Key。Groq 提供免费额度，日常使用绰绰有余。",
        "provider.help.deepseek": "前往 platform.deepseek.com → API Keys。DeepSeek 提供高性价比的中文 LLM。",
        "provider.help.moonshot": "前往 platform.moonshot.ai → API Keys。Moonshot (Kimi) 支持中文语境优化。",
        "provider.help.gemini": "前往 aistudio.google.com → Get API Key。Gemini 提供免费额度。",
        "provider.help.apple": "使用 macOS 26 内置的 Apple Intelligence 本机模型（约 3B）。免费、离线可用、内容不离开这台电脑。需 Apple Silicon 并在「系统设置」开启 Apple Intelligence。",
        "provider.help.ollama": "请确保 Ollama 已在本机运行（默认 http://localhost:11434）。不需要 API Key。",
        "provider.help.custom": "填入兼容 OpenAI Chat Completions API 格式的 endpoint URL 和模型名称。",

        "error.no-api-key": "未设置 API Key",
        "error.invalid-response": "API 响应格式错误",
        "error.api": "API 错误：%@",
        "error.network": "网络错误：%@",
        "error.empty-audio": "音频数据为空",
        "error.rate-limited": "已达 API 用量上限（HTTP 429）",
        "error.llm-invalid-response": "LLM API 响应格式错误",
        "error.llm-api": "LLM API 错误：%@",
        "error.llm-rate-limited": "已达 LLM API 用量上限（HTTP 429）",
        "error.invalid-url": "无效的 URL: %@",
        "error.unknown": "未知错误",
        "error.apple.os-version": "需要 macOS 26 以上版本",
        "error.apple.unsupported-device": "此设备不支持 Apple Intelligence（需 Apple Silicon）",
        "error.apple.not-enabled": "请先在「系统设置」开启 Apple Intelligence",
        "error.apple.model-not-ready": "模型准备中（可能正在下载），请稍后再试",
        "error.apple.unavailable": "Apple Intelligence 当前无法使用",

        "quota.title": "%@ 已达用量上限",
        "quota.llm-switch": "语义修正（LLM）供应商 %@ 的所有账号均报告已达额度上限（HTTP 429）。要切换到 %@ 吗？",
        "quota.llm-none": "语义修正（LLM）供应商 %@ 的所有账号均报告已达额度上限（HTTP 429）。没有其他已设置 API Key 的供应商可切换，请至「API 设置」添加其他供应商或账号的 Key。",
        "quota.stt-switch": "语音识别（STT）供应商 %@ 的所有账号均报告已达额度上限（HTTP 429）。要切换到 %@ 吗？",
        "quota.stt-none": "语音识别（STT）供应商 %@ 的所有账号均报告已达额度上限（HTTP 429）。没有其他已设置 API Key 的供应商可切换，请至「API 设置」添加其他供应商或账号的 Key。",
        "quota.switch-to": "切换到 %@",
        "quota.later": "稍后再说",
        "quota.got-it": "知道了",
    ]

    // MARK: - English

    static let en: [String: String] = [
        "menu.hold-to-speak": "Hold %@ to speak",
        "menu.preferences": "Preferences…",
        "menu.quit": "Quit TypeTop",
        "window.preferences": "TypeTop Preferences",
        "tab.general": "General",
        "tab.api": "API",
        "tab.language": "Language",
        "tab.vocabulary": "Vocabulary",

        "common.cancel": "Cancel",
        "common.save": "Save",
        "common.add": "Add",
        "common.ok": "OK",
        "common.reset-default": "Reset to default",

        "general.section.shortcut": "Shortcut",
        "general.push-to-talk-key": "Push-to-talk key",
        "general.interface-language": "Interface language",
        "general.section.permissions": "Permissions",
        "general.accessibility": "Accessibility",
        "general.microphone": "Microphone",
        "general.granted": "Granted",
        "general.open-settings": "Open Settings",
        "general.request-access": "Request access",
        "general.section.behavior": "Behavior",
        "general.play-sounds": "Play sound effects",
        "general.mute-system-audio": "Mute system audio while recording",
        "general.launch-at-login": "Launch at login",
        "general.section.about": "About",
        "general.version": "Version",
        "general.tagline": "Speak it, type it well",

        "key.right-command": "Right ⌘",
        "key.left-command": "Left ⌘",
        "key.right-option": "Right ⌥",
        "key.left-option": "Left ⌥",
        "key.right-control": "Right ⌃",
        "key.left-control": "Left ⌃",

        "api.section.stt": "Speech recognition (STT) — Groq",
        "api.section.llm": "Text correction (LLM) — %@",
        "api.test-connection": "Test connection",
        "api.test-llm-connection": "Test LLM connection",
        "api.model": "Model",
        "api.model-name": "Model name",
        "api.status": "Status",
        "api.available": "Available",
        "api.llm-provider": "LLM provider",
        "api.open-groq-console": "Open Groq Console",
        "api.open-website": "Open the %@ website",
        "api.howto.title": "How to get a Groq API key:",
        "api.howto.step1": "1. Go to console.groq.com and sign up / log in",
        "api.howto.step2": "2. In the sidebar choose “API Keys” → “Create API Key”",
        "api.howto.step3": "3. Copy the key starting with gsk_ and paste it above",
        "api.howto.multi-account": "Add keys from several accounts — TypeTop switches automatically when one runs out of free quota.",
        "api.failover-note": "When an account hits its quota (HTTP 429), TypeTop switches to the next one.",
        "api.add-account": "Add account",
        "api.account-n": "Account %d",
        "api.account-name": "Account name",
        "api.name": "Name",
        "api.in-use": "In use",
        "api.set-active": "Set as active",
        "api.edit-key": "View / edit name and key",
        "api.collapse": "Collapse",
        "api.delete-account": "Delete this account",
        "api.copy-message": "Copy message",

        "usage.section": "Today’s usage (local count)",
        "usage.stt": "Speech recognition (%@)",
        "usage.llm": "Text correction (%@)",
        "usage.requests": "%@ requests",
        "usage.requests-tokens": "%@ requests / %@ tokens",
        "usage.groq-stt-remaining": "Groq speech recognition quota left%@",
        "usage.groq-llm-remaining": "Groq text correction quota left%@",
        "usage.note": "Request and token counts are tracked locally by this app and cover only the account currently in use. The Groq quota comes from Groq’s own API responses. For other providers, check their consoles (Gemini: aistudio.google.com/rate-limit).",

        "test.stt-ok": "Groq STT connected! (%@s%@)",
        "test.stt-fail": "Groq STT: %@",
        "test.apple-ok": "Apple on-device model is available! (response: %@)",
        "test.apple-fail": "Apple on-device model: %@",
        "test.llm-ok": "%@ LLM connected! (response: %@%@)",
        "test.llm-fail": "%@ LLM: %@",

        "lang.section.primary": "Primary language",
        "lang.recognition-language": "Recognition language",
        "lang.mixed-mode": "Mixed-language mode",
        "lang.mixed-mode-note": "With mixed mode on, Whisper recognizes your primary language and English together",
        "lang.section.text": "Text processing",
        "lang.auto-space": "Auto-space between CJK and Latin",
        "lang.auto-space-note": "e.g. 「使用React框架」→「使用 React 框架」",
        "lang.punctuation-style": "Punctuation style",
        "lang.punctuation-note": "Full-width: ，。！？　Half-width: ,.!?　None: strip all　Keep: no conversion",
        "lang.section.whisper-prompt": "Whisper prompt",
        "lang.whisper-prompt-note": "The prompt gives Whisper context. Add proper nouns you say often to improve accuracy — e.g. “TypeTop, React, Python” makes Whisper favor those terms.",
        "lang.section.llm": "LLM post-processing",
        "lang.enable-llm": "Enable LLM correction",
        "lang.model-in-use": "Model in use",
        "lang.need-api-key": "Add your %@ API key on the API tab first",
        "lang.provider-note": "Speech recognition (STT) and text correction (LLM) can use different providers — for example Groq for transcription and OpenAI GPT for correction.",
        "lang.temperature": "Temperature",
        "lang.temperature-note": "Lower is more consistent, higher more varied. For fixing typos, 0–0.3 works best.",
        "lang.section.system-prompt": "LLM system prompt",
        "lang.correction-level": "Correction level",
        "lang.level-note": "Picking a level applies its default prompt; you can still edit it by hand.",
        "lang.reset-level-default": "Reset to this level’s default",

        "vocab.search": "Search entries…",
        "vocab.count": "%@ entries",
        "vocab.export-json": "Export vocabulary (JSON)…",
        "vocab.export-zhuyin": "Export Zhuyin dictionary (.txt)…",
        "vocab.import": "Import vocabulary…",
        "vocab.empty-title": "No entries",
        "vocab.empty-line1": "Tap + to add a replacement rule",
        "vocab.empty-line2": "Fixes words the recognizer keeps getting wrong\ne.g. “太好了 → TypeTop”, “派森 → Python”",
        "vocab.import-error": "Import failed",
        "vocab.default-filename": "personal-dictionary.txt",
        "vocab.new-entry": "New entry",
        "vocab.edit-entry": "Edit entry",
        "vocab.source": "Misrecognized text (from)",
        "vocab.target": "Correct text (to)",
        "vocab.note": "Note (optional)",
        "vocab.enabled": "Enabled",

        "state.idle": "Ready",
        "state.recording": "Recording",
        "state.recording-ellipsis": "Recording…",
        "state.transcribing": "Transcribing",
        "state.transcribing-ellipsis": "Transcribing…",
        "state.cancelled": "Cancelled",
        "state.done": "Done: %@…",
        "state.error": "Error: %@",

        "level.none": "None",
        "level.light": "Light",
        "level.medium": "Medium",
        "level.heavy": "Heavy",
        "level.none.desc": "Punctuation only, wording untouched",
        "level.light.desc": "Fix typos and punctuation, keep your spoken style",
        "level.medium.desc": "Rewrite in clean prose, drop filler words",
        "level.heavy.desc": "Condense heavily and restructure sentences",

        "punct.full": "Full-width",
        "punct.half": "Half-width",
        "punct.none": "No punctuation",
        "punct.keep": "Keep as-is",

        "provider.apple": "Apple on-device model",
        "provider.ollama": "Ollama (local)",
        "provider.custom": "Custom",
        "provider.apple-model": "Built-in system model (on-device)",
        "provider.custom-key-placeholder": "API key (if required)",
        "provider.help.openai": "Go to platform.openai.com → API Keys → Create new secret key. Requires prepaid credit; gpt-4o-mini costs very little.",
        "provider.help.groq": "Go to console.groq.com → API Keys → Create API Key. Groq’s free tier is plenty for everyday use.",
        "provider.help.deepseek": "Go to platform.deepseek.com → API Keys. DeepSeek is a cost-effective, Chinese-capable LLM.",
        "provider.help.moonshot": "Go to platform.moonshot.ai → API Keys. Moonshot (Kimi) is tuned for Chinese context.",
        "provider.help.gemini": "Go to aistudio.google.com → Get API Key. Gemini has a free tier.",
        "provider.help.apple": "Uses the Apple Intelligence on-device model (~3B) built into macOS 26. Free, works offline, and nothing leaves this Mac. Requires Apple Silicon with Apple Intelligence enabled in System Settings.",
        "provider.help.ollama": "Make sure Ollama is running locally (default http://localhost:11434). No API key needed.",
        "provider.help.custom": "Enter an endpoint URL and model name compatible with the OpenAI Chat Completions API.",

        "error.no-api-key": "No API key set",
        "error.invalid-response": "Unexpected API response format",
        "error.api": "API error: %@",
        "error.network": "Network error: %@",
        "error.empty-audio": "Audio data is empty",
        "error.rate-limited": "API quota reached (HTTP 429)",
        "error.llm-invalid-response": "Unexpected LLM API response format",
        "error.llm-api": "LLM API error: %@",
        "error.llm-rate-limited": "LLM API quota reached (HTTP 429)",
        "error.invalid-url": "Invalid URL: %@",
        "error.unknown": "Unknown error",
        "error.apple.os-version": "Requires macOS 26 or later",
        "error.apple.unsupported-device": "This Mac doesn’t support Apple Intelligence (Apple Silicon required)",
        "error.apple.not-enabled": "Turn on Apple Intelligence in System Settings first",
        "error.apple.model-not-ready": "The model is getting ready (it may still be downloading) — try again shortly",
        "error.apple.unavailable": "Apple Intelligence is currently unavailable",

        "quota.title": "%@ quota reached",
        "quota.llm-switch": "Every account for the text-correction (LLM) provider %@ reports its quota is used up (HTTP 429). Switch to %@?",
        "quota.llm-none": "Every account for the text-correction (LLM) provider %@ reports its quota is used up (HTTP 429). No other provider has an API key configured — add one on the API tab.",
        "quota.stt-switch": "Every account for the speech-recognition (STT) provider %@ reports its quota is used up (HTTP 429). Switch to %@?",
        "quota.stt-none": "Every account for the speech-recognition (STT) provider %@ reports its quota is used up (HTTP 429). No other provider has an API key configured — add one on the API tab.",
        "quota.switch-to": "Switch to %@",
        "quota.later": "Not now",
        "quota.got-it": "OK",
    ]

    // MARK: - 日本語

    static let ja: [String: String] = [
        "menu.hold-to-speak": "%@ を押しながら話す",
        "menu.preferences": "環境設定…",
        "menu.quit": "TypeTop を終了",
        "window.preferences": "TypeTop 環境設定",
        "tab.general": "一般",
        "tab.api": "API",
        "tab.language": "言語",
        "tab.vocabulary": "単語登録",

        "common.cancel": "キャンセル",
        "common.save": "保存",
        "common.add": "追加",
        "common.ok": "OK",
        "common.reset-default": "デフォルトに戻す",

        "general.section.shortcut": "ショートカット",
        "general.push-to-talk-key": "押しながら話すキー",
        "general.interface-language": "表示言語",
        "general.section.permissions": "アクセス権",
        "general.accessibility": "アクセシビリティ",
        "general.microphone": "マイク",
        "general.granted": "許可済み",
        "general.open-settings": "設定を開く",
        "general.request-access": "許可をリクエスト",
        "general.section.behavior": "動作",
        "general.play-sounds": "効果音を鳴らす",
        "general.mute-system-audio": "録音中はシステム音声をミュート",
        "general.launch-at-login": "ログイン時に起動",
        "general.section.about": "このアプリについて",
        "general.version": "バージョン",
        "general.tagline": "話すだけで、きちんと入力",

        "key.right-command": "右 ⌘",
        "key.left-command": "左 ⌘",
        "key.right-option": "右 ⌥",
        "key.left-option": "左 ⌥",
        "key.right-control": "右 ⌃",
        "key.left-control": "左 ⌃",

        "api.section.stt": "音声認識（STT）— Groq",
        "api.section.llm": "文章補正（LLM）— %@",
        "api.test-connection": "接続テスト",
        "api.test-llm-connection": "LLM 接続テスト",
        "api.model": "モデル",
        "api.model-name": "モデル名",
        "api.status": "状態",
        "api.available": "利用可能",
        "api.llm-provider": "LLM プロバイダ",
        "api.open-groq-console": "Groq Console を開く",
        "api.open-website": "%@ の公式サイトを開く",
        "api.howto.title": "Groq API キーの取得手順：",
        "api.howto.step1": "1. console.groq.com で登録／ログイン",
        "api.howto.step2": "2. 左メニューの「API Keys」→「Create API Key」",
        "api.howto.step3": "3. gsk_ で始まるキーをコピーして上の欄に貼り付け",
        "api.howto.multi-account": "複数アカウントのキーを登録でき、無料枠を使い切ると自動で切り替わります。",
        "api.failover-note": "上限（HTTP 429）に達すると次のアカウントへ自動的に切り替わります。",
        "api.add-account": "アカウントを追加",
        "api.account-n": "アカウント %d",
        "api.account-name": "アカウント名",
        "api.name": "名前",
        "api.in-use": "使用中",
        "api.set-active": "使用中にする",
        "api.edit-key": "名前とキーを表示／編集",
        "api.collapse": "閉じる",
        "api.delete-account": "このアカウントを削除",
        "api.copy-message": "メッセージをコピー",

        "usage.section": "本日の使用量（ローカル集計）",
        "usage.stt": "音声認識（%@）",
        "usage.llm": "文章補正（%@）",
        "usage.requests": "%@ 回",
        "usage.requests-tokens": "%@ 回 / %@ トークン",
        "usage.groq-stt-remaining": "Groq 音声認識の残り枠%@",
        "usage.groq-llm-remaining": "Groq 文章補正の残り枠%@",
        "usage.note": "回数とトークン数はこのアプリのローカル集計で、使用中のアカウントのみが対象です。Groq の残り枠は公式レスポンスの値です。他社の残量は各コンソールでご確認ください（Gemini：aistudio.google.com/rate-limit）。",

        "test.stt-ok": "Groq STT に接続できました（%@ 秒%@）",
        "test.stt-fail": "Groq STT：%@",
        "test.apple-ok": "Apple オンデバイスモデルが利用できます（応答：%@）",
        "test.apple-fail": "Apple オンデバイスモデル：%@",
        "test.llm-ok": "%@ LLM に接続できました（応答：%@%@）",
        "test.llm-fail": "%@ LLM：%@",

        "lang.section.primary": "主な言語",
        "lang.recognition-language": "認識する言語",
        "lang.mixed-mode": "多言語ミックスモード",
        "lang.mixed-mode-note": "オンにすると、主な言語と英語を同時に認識します",
        "lang.section.text": "テキスト処理",
        "lang.auto-space": "CJK と英数字の間に自動でスペース",
        "lang.auto-space-note": "例：「使用React框架」→「使用 React 框架」",
        "lang.punctuation-style": "句読点のスタイル",
        "lang.punctuation-note": "全角：，。！？　半角：,.!?　なし：すべて削除　そのまま：変換しない",
        "lang.section.whisper-prompt": "Whisper プロンプト",
        "lang.whisper-prompt-note": "プロンプトは Whisper に文脈を伝えます。よく使う固有名詞を入れると精度が上がります（例：「TypeTop, React, Python」）。",
        "lang.section.llm": "LLM による後処理",
        "lang.enable-llm": "LLM 補正を有効にする",
        "lang.model-in-use": "使用モデル",
        "lang.need-api-key": "先に API タブで %@ の API キーを入力してください",
        "lang.provider-note": "音声認識（STT）と文章補正（LLM）は別々のプロバイダを使えます。例：文字起こしは Groq、補正は OpenAI GPT。",
        "lang.temperature": "温度",
        "lang.temperature-note": "低いほど安定し、高いほど変化します。誤字修正には 0〜0.3 が最適です。",
        "lang.section.system-prompt": "LLM システムプロンプト",
        "lang.correction-level": "補正の強さ",
        "lang.level-note": "強さを選ぶと既定のプロンプトが入ります。手動で編集もできます。",
        "lang.reset-level-default": "この強さの既定値に戻す",

        "vocab.search": "単語を検索…",
        "vocab.count": "%@ 件",
        "vocab.export-json": "単語リストを書き出す (JSON)…",
        "vocab.export-zhuyin": "注音辞書を書き出す (.txt)…",
        "vocab.import": "単語リストを読み込む…",
        "vocab.empty-title": "単語がありません",
        "vocab.empty-line1": "＋ で置き換えルールを追加",
        "vocab.empty-line2": "認識をよく間違える単語を修正します\n例：「太好了 → TypeTop」「派森 → Python」",
        "vocab.import-error": "読み込みエラー",
        "vocab.default-filename": "個人辞書.txt",
        "vocab.new-entry": "単語を追加",
        "vocab.edit-entry": "単語を編集",
        "vocab.source": "誤認識された文字（変換元）",
        "vocab.target": "正しい文字（変換先）",
        "vocab.note": "メモ（任意）",
        "vocab.enabled": "有効",

        "state.idle": "待機中",
        "state.recording": "録音中",
        "state.recording-ellipsis": "録音中…",
        "state.transcribing": "認識中",
        "state.transcribing-ellipsis": "認識中…",
        "state.cancelled": "キャンセルしました",
        "state.done": "完了：%@…",
        "state.error": "エラー：%@",

        "level.none": "なし",
        "level.light": "弱",
        "level.medium": "中",
        "level.heavy": "強",
        "level.none.desc": "句読点のみ追加し、語句はそのまま",
        "level.light.desc": "誤字と句読点を直し、話し言葉の雰囲気は残す",
        "level.medium.desc": "書き言葉に整え、余分な言葉を削除",
        "level.heavy.desc": "大幅に凝縮し、文の構成を組み替える",

        "punct.full": "全角",
        "punct.half": "半角",
        "punct.none": "句読点なし",
        "punct.keep": "そのまま",

        "provider.apple": "Apple オンデバイスモデル",
        "provider.ollama": "Ollama（ローカル）",
        "provider.custom": "カスタム",
        "provider.apple-model": "OS 内蔵モデル（オンデバイス）",
        "provider.custom-key-placeholder": "API キー（必要な場合）",
        "provider.help.openai": "platform.openai.com → API Keys → Create new secret key。事前チャージが必要ですが、gpt-4o-mini はごく低コストです。",
        "provider.help.groq": "console.groq.com → API Keys → Create API Key。Groq の無料枠は日常利用に十分です。",
        "provider.help.deepseek": "platform.deepseek.com → API Keys。DeepSeek は中国語に強く、コスパに優れた LLM です。",
        "provider.help.moonshot": "platform.moonshot.ai → API Keys。Moonshot (Kimi) は中国語の文脈に最適化されています。",
        "provider.help.gemini": "aistudio.google.com → Get API Key。Gemini には無料枠があります。",
        "provider.help.apple": "macOS 26 内蔵の Apple Intelligence オンデバイスモデル（約 3B）を使います。無料・オフライン対応で、内容がこの Mac の外に出ません。Apple Silicon と「システム設定」での Apple Intelligence 有効化が必要です。",
        "provider.help.ollama": "Ollama をローカルで実行しておいてください（既定 http://localhost:11434）。API キーは不要です。",
        "provider.help.custom": "OpenAI Chat Completions API 互換のエンドポイント URL とモデル名を入力してください。",

        "error.no-api-key": "API キーが未設定です",
        "error.invalid-response": "API レスポンスの形式が不正です",
        "error.api": "API エラー：%@",
        "error.network": "ネットワークエラー：%@",
        "error.empty-audio": "音声データが空です",
        "error.rate-limited": "API の利用上限に達しました（HTTP 429）",
        "error.llm-invalid-response": "LLM API レスポンスの形式が不正です",
        "error.llm-api": "LLM API エラー：%@",
        "error.llm-rate-limited": "LLM API の利用上限に達しました（HTTP 429）",
        "error.invalid-url": "無効な URL: %@",
        "error.unknown": "不明なエラー",
        "error.apple.os-version": "macOS 26 以降が必要です",
        "error.apple.unsupported-device": "この Mac は Apple Intelligence に対応していません（Apple Silicon が必要）",
        "error.apple.not-enabled": "先に「システム設定」で Apple Intelligence をオンにしてください",
        "error.apple.model-not-ready": "モデルを準備中です（ダウンロード中の可能性があります）。しばらくしてからお試しください",
        "error.apple.unavailable": "Apple Intelligence は現在利用できません",

        "quota.title": "%@ が利用上限に達しました",
        "quota.llm-switch": "文章補正（LLM）プロバイダ %@ のすべてのアカウントが上限（HTTP 429）に達しました。%@ に切り替えますか？",
        "quota.llm-none": "文章補正（LLM）プロバイダ %@ のすべてのアカウントが上限（HTTP 429）に達しました。切り替え先となる API キー設定済みのプロバイダがありません。「API」タブでキーを追加してください。",
        "quota.stt-switch": "音声認識（STT）プロバイダ %@ のすべてのアカウントが上限（HTTP 429）に達しました。%@ に切り替えますか？",
        "quota.stt-none": "音声認識（STT）プロバイダ %@ のすべてのアカウントが上限（HTTP 429）に達しました。切り替え先となる API キー設定済みのプロバイダがありません。「API」タブでキーを追加してください。",
        "quota.switch-to": "%@ に切り替える",
        "quota.later": "あとで",
        "quota.got-it": "OK",
    ]

    // MARK: - 한국어

    static let ko: [String: String] = [
        "menu.hold-to-speak": "%@ 를 누른 채 말하기",
        "menu.preferences": "환경설정…",
        "menu.quit": "TypeTop 종료",
        "window.preferences": "TypeTop 환경설정",
        "tab.general": "일반",
        "tab.api": "API",
        "tab.language": "언어",
        "tab.vocabulary": "단어장",

        "common.cancel": "취소",
        "common.save": "저장",
        "common.add": "추가",
        "common.ok": "확인",
        "common.reset-default": "기본값으로 재설정",

        "general.section.shortcut": "단축키",
        "general.push-to-talk-key": "말하기 단축키",
        "general.interface-language": "표시 언어",
        "general.section.permissions": "권한",
        "general.accessibility": "손쉬운 사용",
        "general.microphone": "마이크",
        "general.granted": "허용됨",
        "general.open-settings": "설정 열기",
        "general.request-access": "권한 요청",
        "general.section.behavior": "동작",
        "general.play-sounds": "효과음 재생",
        "general.mute-system-audio": "녹음 중 시스템 소리 음소거",
        "general.launch-at-login": "로그인 시 자동 실행",
        "general.section.about": "정보",
        "general.version": "버전",
        "general.tagline": "말하면, 제대로 입력됩니다",

        "key.right-command": "오른쪽 ⌘",
        "key.left-command": "왼쪽 ⌘",
        "key.right-option": "오른쪽 ⌥",
        "key.left-option": "왼쪽 ⌥",
        "key.right-control": "오른쪽 ⌃",
        "key.left-control": "왼쪽 ⌃",

        "api.section.stt": "음성 인식(STT) — Groq",
        "api.section.llm": "문장 교정(LLM) — %@",
        "api.test-connection": "연결 테스트",
        "api.test-llm-connection": "LLM 연결 테스트",
        "api.model": "모델",
        "api.model-name": "모델 이름",
        "api.status": "상태",
        "api.available": "사용 가능",
        "api.llm-provider": "LLM 공급자",
        "api.open-groq-console": "Groq Console 열기",
        "api.open-website": "%@ 웹사이트 열기",
        "api.howto.title": "Groq API 키 발급 방법:",
        "api.howto.step1": "1. console.groq.com 에서 가입 / 로그인",
        "api.howto.step2": "2. 왼쪽 메뉴에서 “API Keys” → “Create API Key”",
        "api.howto.step3": "3. gsk_ 로 시작하는 키를 복사해 위 칸에 붙여넣기",
        "api.howto.multi-account": "여러 계정의 키를 등록할 수 있으며, 무료 한도를 다 쓰면 자동으로 전환됩니다.",
        "api.failover-note": "한도(HTTP 429)에 도달하면 다음 계정으로 자동 전환됩니다.",
        "api.add-account": "계정 추가",
        "api.account-n": "계정 %d",
        "api.account-name": "계정 이름",
        "api.name": "이름",
        "api.in-use": "사용 중",
        "api.set-active": "사용 중으로 지정",
        "api.edit-key": "이름·키 보기 / 편집",
        "api.collapse": "접기",
        "api.delete-account": "이 계정 삭제",
        "api.copy-message": "메시지 복사",

        "usage.section": "오늘 사용량(로컬 집계)",
        "usage.stt": "음성 인식(%@)",
        "usage.llm": "문장 교정(%@)",
        "usage.requests": "%@ 회",
        "usage.requests-tokens": "%@ 회 / %@ 토큰",
        "usage.groq-stt-remaining": "Groq 음성 인식 잔여 한도%@",
        "usage.groq-llm-remaining": "Groq 문장 교정 잔여 한도%@",
        "usage.note": "횟수와 토큰은 이 앱의 로컬 집계이며 현재 사용 중인 계정만 반영합니다. Groq 잔여 한도는 공식 응답 값입니다. 다른 공급자의 한도는 각 콘솔에서 확인하세요(Gemini: aistudio.google.com/rate-limit).",

        "test.stt-ok": "Groq STT 연결 성공! (%@초%@)",
        "test.stt-fail": "Groq STT: %@",
        "test.apple-ok": "Apple 온디바이스 모델 사용 가능! (응답: %@)",
        "test.apple-fail": "Apple 온디바이스 모델: %@",
        "test.llm-ok": "%@ LLM 연결 성공! (응답: %@%@)",
        "test.llm-fail": "%@ LLM: %@",

        "lang.section.primary": "주 언어",
        "lang.recognition-language": "인식 언어",
        "lang.mixed-mode": "다국어 혼합 모드",
        "lang.mixed-mode-note": "켜면 주 언어와 영어를 함께 인식합니다",
        "lang.section.text": "텍스트 처리",
        "lang.auto-space": "한중일 문자와 영문 사이 자동 띄어쓰기",
        "lang.auto-space-note": "예: 「使用React框架」→「使用 React 框架」",
        "lang.punctuation-style": "문장 부호 스타일",
        "lang.punctuation-note": "전각: ，。！？　반각: ,.!?　없음: 모두 제거　유지: 변환 안 함",
        "lang.section.whisper-prompt": "Whisper 프롬프트",
        "lang.whisper-prompt-note": "프롬프트는 Whisper에 문맥을 알려 줍니다. 자주 쓰는 고유명사를 넣으면 정확도가 올라갑니다(예: “TypeTop, React, Python”).",
        "lang.section.llm": "LLM 후처리",
        "lang.enable-llm": "LLM 교정 사용",
        "lang.model-in-use": "사용 모델",
        "lang.need-api-key": "먼저 API 탭에서 %@ API 키를 입력하세요",
        "lang.provider-note": "음성 인식(STT)과 문장 교정(LLM)은 서로 다른 공급자를 쓸 수 있습니다. 예: 받아쓰기는 Groq, 교정은 OpenAI GPT.",
        "lang.temperature": "온도",
        "lang.temperature-note": "낮을수록 일관되고 높을수록 다양해집니다. 오타 교정은 0~0.3을 권장합니다.",
        "lang.section.system-prompt": "LLM 시스템 프롬프트",
        "lang.correction-level": "교정 강도",
        "lang.level-note": "강도를 고르면 기본 프롬프트가 적용되며, 직접 수정할 수도 있습니다.",
        "lang.reset-level-default": "현재 강도의 기본값으로 재설정",

        "vocab.search": "단어 검색…",
        "vocab.count": "%@개 항목",
        "vocab.export-json": "단어장 내보내기 (JSON)…",
        "vocab.export-zhuyin": "주음 사전 내보내기 (.txt)…",
        "vocab.import": "단어장 가져오기…",
        "vocab.empty-title": "항목 없음",
        "vocab.empty-line1": "+ 를 눌러 치환 규칙을 추가하세요",
        "vocab.empty-line2": "자주 잘못 인식되는 단어를 고칩니다\n예: 「太好了 → TypeTop」「派森 → Python」",
        "vocab.import-error": "가져오기 오류",
        "vocab.default-filename": "개인사전.txt",
        "vocab.new-entry": "단어 추가",
        "vocab.edit-entry": "단어 편집",
        "vocab.source": "잘못 인식된 텍스트(원본)",
        "vocab.target": "올바른 텍스트(대상)",
        "vocab.note": "메모(선택)",
        "vocab.enabled": "사용",

        "state.idle": "대기 중",
        "state.recording": "녹음 중",
        "state.recording-ellipsis": "녹음 중…",
        "state.transcribing": "인식 중",
        "state.transcribing-ellipsis": "인식 중…",
        "state.cancelled": "취소됨",
        "state.done": "완료: %@…",
        "state.error": "오류: %@",

        "level.none": "없음",
        "level.light": "약하게",
        "level.medium": "보통",
        "level.heavy": "강하게",
        "level.none.desc": "문장 부호만 추가하고 표현은 그대로",
        "level.light.desc": "오타와 문장 부호만 고치고 말투는 유지",
        "level.medium.desc": "문어체로 다듬고 군더더기 제거",
        "level.heavy.desc": "대폭 압축하고 문장 구조를 재구성",

        "punct.full": "전각",
        "punct.half": "반각",
        "punct.none": "부호 없음",
        "punct.keep": "그대로 유지",

        "provider.apple": "Apple 온디바이스 모델",
        "provider.ollama": "Ollama(로컬)",
        "provider.custom": "사용자 지정",
        "provider.apple-model": "시스템 내장 모델(온디바이스)",
        "provider.custom-key-placeholder": "API 키(필요한 경우)",
        "provider.help.openai": "platform.openai.com → API Keys → Create new secret key. 선불 충전이 필요하지만 gpt-4o-mini는 비용이 아주 낮습니다.",
        "provider.help.groq": "console.groq.com → API Keys → Create API Key. Groq 무료 한도면 일상 사용에 충분합니다.",
        "provider.help.deepseek": "platform.deepseek.com → API Keys. DeepSeek은 가성비 좋은 중국어 특화 LLM입니다.",
        "provider.help.moonshot": "platform.moonshot.ai → API Keys. Moonshot(Kimi)은 중국어 문맥에 최적화되어 있습니다.",
        "provider.help.gemini": "aistudio.google.com → Get API Key. Gemini에는 무료 한도가 있습니다.",
        "provider.help.apple": "macOS 26에 내장된 Apple Intelligence 온디바이스 모델(약 3B)을 사용합니다. 무료이고 오프라인에서 동작하며 내용이 이 Mac을 벗어나지 않습니다. Apple Silicon과 시스템 설정에서 Apple Intelligence 활성화가 필요합니다.",
        "provider.help.ollama": "Ollama가 로컬에서 실행 중인지 확인하세요(기본 http://localhost:11434). API 키는 필요 없습니다.",
        "provider.help.custom": "OpenAI Chat Completions API 호환 엔드포인트 URL과 모델 이름을 입력하세요.",

        "error.no-api-key": "API 키가 설정되지 않았습니다",
        "error.invalid-response": "API 응답 형식이 올바르지 않습니다",
        "error.api": "API 오류: %@",
        "error.network": "네트워크 오류: %@",
        "error.empty-audio": "오디오 데이터가 비어 있습니다",
        "error.rate-limited": "API 사용 한도에 도달했습니다(HTTP 429)",
        "error.llm-invalid-response": "LLM API 응답 형식이 올바르지 않습니다",
        "error.llm-api": "LLM API 오류: %@",
        "error.llm-rate-limited": "LLM API 사용 한도에 도달했습니다(HTTP 429)",
        "error.invalid-url": "잘못된 URL: %@",
        "error.unknown": "알 수 없는 오류",
        "error.apple.os-version": "macOS 26 이상이 필요합니다",
        "error.apple.unsupported-device": "이 Mac은 Apple Intelligence를 지원하지 않습니다(Apple Silicon 필요)",
        "error.apple.not-enabled": "먼저 시스템 설정에서 Apple Intelligence를 켜세요",
        "error.apple.model-not-ready": "모델을 준비 중입니다(다운로드 중일 수 있음). 잠시 후 다시 시도하세요",
        "error.apple.unavailable": "Apple Intelligence를 현재 사용할 수 없습니다",

        "quota.title": "%@ 사용 한도 도달",
        "quota.llm-switch": "문장 교정(LLM) 공급자 %@의 모든 계정이 한도(HTTP 429)에 도달했습니다. %@(으)로 전환할까요?",
        "quota.llm-none": "문장 교정(LLM) 공급자 %@의 모든 계정이 한도(HTTP 429)에 도달했습니다. 전환할 수 있는 API 키가 설정된 공급자가 없습니다. API 탭에서 키를 추가하세요.",
        "quota.stt-switch": "음성 인식(STT) 공급자 %@의 모든 계정이 한도(HTTP 429)에 도달했습니다. %@(으)로 전환할까요?",
        "quota.stt-none": "음성 인식(STT) 공급자 %@의 모든 계정이 한도(HTTP 429)에 도달했습니다. 전환할 수 있는 API 키가 설정된 공급자가 없습니다. API 탭에서 키를 추가하세요.",
        "quota.switch-to": "%@(으)로 전환",
        "quota.later": "나중에",
        "quota.got-it": "확인",
    ]
}
