name: TypeTop
options:
  bundleIdPrefix: com.typetop
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.10"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: true
    CODE_SIGN_IDENTITY: "-"
    PRODUCT_BUNDLE_IDENTIFIER: com.typetop.app

targets:
  TypeTop:
    type: application
    platform: macOS
    sources:
      - TypeTop
    settings:
      base:
        INFOPLIST_FILE: TypeTop/Resources/Info.plist
        PRODUCT_NAME: TypeTop
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_APP_SANDBOX: false
        CODE_SIGN_ENTITLEMENTS: TypeTop/Resources/TypeTop.entitlements
    entitlements:
      path: TypeTop/Resources/TypeTop.entitlements
      properties:
        com.apple.security.device.audio-input: true
